#! /usr/bin/env python
# encoding:utf-8

APPNAME = 'kvdb'
VERSION = '0.1'

#top = '.'
#out = 'bin'

CFLAGS = []

def options(opt):
    opt.load('compiler_c compiler_cxx')


def configure(conf):
    conf.load('compiler_c compiler_cxx')
    
    conf.env.PREFIX='/usr'
    conf.env.LIBDIR='/usr/lib'
    conf.env.INCLUDEDIR='/usr/include'
    
    conf.env.LIB_PTHREAD = 'pthread'
    conf.check_cfg(atleast_pkgconfig_version='0.0.0')
    conf.check_cfg(package='mpaxos', uselib_store='MPAXOS', args=['--cflags', '--libs'])
    conf.check_cfg(package='leveldb', uselib_store='LEVELDB', args=['--cflags', '--libs'])
    # TODO c++11 check


def build(bld):
    bld.stlib(source=bld.path.ant_glob('kvdb.cpp operation.cpp'), 
            target='kvdb', 
            use=['MPAXOS', 'LEVELDB'], 
            cxxflags = ['-std=c++11'],
            includes='. ../include', 
            install_path='${LIBDIR}')

    bld.install_files('${PREFIX}/include', bld.path.parent.ant_glob('include/kvdb/*.h'))
    # TODO install kvdb.pc failed
    bld(features = 'subst',
        source = 'kvdb.pc.in',
        target = 'kvdb.pc',
        encoding = 'utf8',
        intall_path = '${PREFIX}/lib/pkgconfig', 
        CFLAGS = ' '.join(CFLAGS),
        VERSION = '0.0',
        PREFIX = bld.env.PREFIX )

