#! /usr/bin/env python
# encoding:utf-8


def options(opt):
  opt.load('compiler_c')

def configure(conf):
  conf.load('compiler_c')
  conf.check_cfg(atleast_pkgconfig_version='0.0.0')
  conf.check_cfg(package='mpaxos', uselib_store='MPAXOS', args=['--cflags', '--libs'])
  

def build(bld):
  bld.program(source='hello_mpaxos.c', target='hello_mpaxos.out', use='MPAXOS')

